name: Airflow CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check-dag:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Check Python syntax
        run: python -m compileall dags